import { getChatGPTUser,chatGPTSignInPath } from "../chatgpt-auth";
import { SiteHeader,SiteFooter } from "../marketing";
import { JoinForm } from "../workspace";
import { Button } from "@/components/ui/button";
import { roles,roleLabels,type Role } from "@/lib/types";
import { getProfile } from "@/lib/server";
import { ArrowRight } from "lucide-react";
export const dynamic="force-dynamic";
export const metadata={title:"Join the network | SWAY IRL"};
export default async function Join({searchParams}:{searchParams:Promise<{role?:string}>}){const params=await searchParams;const selected=roles.includes(params.role as Role)?params.role as Role:undefined;const user=await getChatGPTUser();const profile=user?await getProfile(user.userId):null;const descriptions:Record<Role,string>={retailer:"Bring SWAY to your store",distributor:"Connect your partner network",brand:"Find your in-store presence",influencer:"Create for the real world"};return <><SiteHeader/><main className="auth-shell"><p className="eyebrow">LET’S MAKE AN INTRODUCTION</p><h1>Join the<br/><em>SWAY pilot.</em></h1><p>{user?"A few details will help us find the right opportunities for you.":"Choose how you’d like to join. You’ll use one account to explore stores and stay connected."}</p>{user?<JoinForm user={user} initialRole={selected} profile={profile}/>:selected?<div className="panel"><span className="badge">{roleLabels[selected]}</span><h2 style={{marginTop:15}}>{descriptions[selected]}.</h2><p style={{marginBottom:22}}>Sign in with ChatGPT, then complete your SWAY partner profile.</p><Button size="lg" asChild><a href={chatGPTSignInPath(`/join?role=${selected}`)} target="_top">Continue with ChatGPT<ArrowRight size={16}/></a></Button><p style={{marginTop:22}}><a className="underlined" href="/join">Choose a different role</a></p></div>:<div className="role-picks">{roles.map(r=><a key={r} className="role-pick" href={`/join?role=${r}`}><strong>{roleLabels[r]} <ArrowRight size={15} className="inline"/></strong><span>{descriptions[r]}</span></a>)}</div>}<p className="fineprint" style={{marginTop:20}}>Already a partner? <a className="underlined" href="/login">Log in</a></p></main><SiteFooter/></>}
