import { getChatGPTUser } from "@/app/chatgpt-auth";
import { database, getProfile, isAdmin } from "@/lib/server";
import { z } from "zod";
import { validateApplication } from "@/lib/application-validation";
import { nextSteps } from "@/lib/onboarding";
export const dynamic="force-dynamic";
const txt=(max=500)=>z.string().trim().max(max);
const required=(max=150)=>txt(max).min(1,"Please complete the required fields.");
const role=z.enum(["retailer","distributor","brand","influencer"]);
const profileSchema=z.object({name:required(),company:required(),role,markets:txt(300).default(""),website:txt(500).refine(v=>!v||/^https?:\/\//i.test(v),"Use a complete link beginning with https://").default(""),notes:txt(3000).default(""),application:z.unknown().optional()});
const storeSchema=z.object({name:required(),city:required(100),state:required(80),type:required(80),capacity:z.number().int().min(1).max(1000).default(30),monthly_cents:z.number().int().min(0).max(100000000).default(12000),annual_cents:z.number().int().min(0).max(100000000).default(100000),status:z.enum(["draft","published","paused"]).default("draft"),partner_id:txt(200).nullable().optional(),description:txt(2000).default("")});
const leadSchema=z.object({name:required(),email:z.string().trim().email().max(254),company:required(),role,stage:z.enum(["New","Contacted","Qualified","Proposal","Won","Lost"]).default("New"),next_step:txt(1000).default(""),follow_up:txt(10).refine(v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v),"Use a valid follow-up date.").default(""),owner:txt(150).default(""),value_cents:z.number().int().min(0).max(1000000000).default(0),notes:txt(6000).default("")});
const storeQuery=`SELECT s.*, (SELECT COUNT(*) FROM requests r WHERE r.store_id=s.id AND r.status='confirmed') AS used, MAX(0,s.capacity-(SELECT COUNT(*) FROM requests r WHERE r.store_id=s.id AND r.status='confirmed')) AS open FROM stores s`;
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}})}
export async function GET(){try{const user=await getChatGPTUser();if(!user)return json({error:"Sign in to view the network."},401);const db=database();const admin=isAdmin(user);const profile=await getProfile(user.userId);
const application=await db.prepare("SELECT stage FROM leads WHERE id=? AND partner_id=?").bind(`signup_${user.userId}`,user.userId).first<{stage:string}>();
const queries=await db.batch([
 db.prepare(`${storeQuery} ${admin?"":"WHERE s.status='published'"} ORDER BY s.name`),
 db.prepare(`SELECT r.*,s.name AS store_name,s.city,s.state${admin?",p.company,p.email":""} FROM requests r JOIN stores s ON s.id=r.store_id ${admin?"JOIN partners p ON p.id=r.partner_id":"WHERE r.partner_id=?"} ORDER BY r.created_at DESC`).bind(...(admin?[]:[user.userId])),
 db.prepare("SELECT id,company,name,role,stage,created_at FROM leads WHERE referrer_id=? ORDER BY created_at DESC").bind(user.userId),
 db.prepare(`${storeQuery} WHERE s.partner_id=? ORDER BY s.created_at DESC`).bind(user.userId),
 db.prepare(admin?"SELECT * FROM partners ORDER BY created_at DESC":"SELECT id FROM partners WHERE 0"),
 db.prepare(admin?"SELECT * FROM leads ORDER BY updated_at DESC":"SELECT id FROM leads WHERE 0")
]);return json({profile,applicationStage:application?.stage||null,isAdmin:admin,stores:queries[0].results,requests:queries[1].results,referrals:queries[2].results,ownStores:queries[3].results,partners:queries[4].results,leads:queries[5].results});
}catch(e){console.error("workspace_load_failed",e);return json({error:"The network is temporarily unavailable. Please try again."},503)}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return json({error:"Your session ended. Please sign in again."},401);
const origin=req.headers.get("origin");if(origin&&origin!==new URL(req.url).origin)return json({error:"This request could not be verified."},403);
if(!req.headers.get("content-type")?.includes("application/json"))return json({error:"Send a JSON request."},415);
const raw=await req.text();if(raw.length>25000)return json({error:"This entry is too long."},413);let body;try{body=JSON.parse(raw)}catch{return json({error:"Invalid request."},400)}
const action=body.action;const db=database(),now=new Date().toISOString(),admin=isAdmin(user);const id=typeof body.id==="string"?body.id.slice(0,200):"";
if(action==="profile.save"){const d=profileSchema.parse(body.data);const existing=await getProfile(user.userId);
const application=d.application!==undefined?JSON.stringify(validateApplication(d.role,d.application)):existing?.role===d.role?(existing.application||"{}"):JSON.stringify(validateApplication(d.role,{}));
if(d.role==="influencer"&&!d.website)return json({error:"Please add your portfolio or social channel link."},400);
await db.batch([
 db.prepare("INSERT INTO partners(id,email,name,company,role,markets,website,notes,application,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name,company=excluded.company,role=excluded.role,markets=excluded.markets,website=excluded.website,notes=excluded.notes,application=excluded.application,updated_at=excluded.updated_at").bind(user.userId,user.email,d.name,d.company,d.role,d.markets,d.website,d.notes,application,now,now),
 db.prepare("INSERT INTO leads(id,partner_id,name,email,company,role,source,stage,next_step,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'New',?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email,company=excluded.company,role=excluded.role,updated_at=excluded.updated_at").bind(`signup_${user.userId}`,user.userId,d.name,user.email,d.company,d.role,"Signup",nextSteps[d.role].review,now,now)
]);return json({ok:true})}
const profile=await getProfile(user.userId);if(!profile&&!admin)return json({error:"Complete your partner profile first."},409);
if(action==="request.create"){if(!profile)return json({error:"Create your partner profile before requesting a spot."},409);const d=z.object({store_id:required(200),campaign:required(200),billing:z.literal("monthly",{errorMap:()=>({message:"Annual pricing is by agreement. Please request a monthly placement or contact the team."})}),notes:txt(3000).default("")}).parse(body.data);const requestId=crypto.randomUUID();
const result=await db.prepare(`INSERT INTO requests(id,partner_id,store_id,campaign,billing,notes,status,rate_cents,created_at,updated_at) SELECT ?,?,?,?,?,?,'requested',CASE WHEN ?='annual' THEN s.annual_cents ELSE s.monthly_cents END,?,? FROM stores s WHERE s.id=? AND s.status='published' AND s.capacity>(SELECT COUNT(*) FROM requests r WHERE r.store_id=s.id AND r.status='confirmed') AND NOT EXISTS(SELECT 1 FROM requests r WHERE r.partner_id=? AND r.store_id=s.id AND r.status IN ('requested','confirmed'))`).bind(requestId,user.userId,d.store_id,d.campaign,d.billing,d.notes,d.billing,now,now,d.store_id,user.userId).run();
if(!result.meta.changes)return json({error:"This store is unavailable, or you already have an active request there. Refresh the network to see the latest status."},409);return json({ok:true,id:requestId})}
if(action==="request.cancel"){const result=await db.prepare("UPDATE requests SET status='cancelled',updated_at=? WHERE id=? AND partner_id=? AND status='requested'").bind(now,id,user.userId).run();if(!result.meta.changes)return json({error:"Only your pending requests can be cancelled. Contact the team about a confirmed placement."},409);return json({ok:true})}
if(action==="store.propose"){if(profile?.role!=="retailer")return json({error:"Store submissions are available to retailer accounts."},403);const d=storeSchema.parse({...body.data,status:"draft",capacity:30,monthly_cents:12000,annual_cents:100000});const storeId=crypto.randomUUID();await db.batch([
 db.prepare("INSERT INTO stores(id,name,city,state,type,capacity,monthly_cents,annual_cents,status,partner_id,description,created_at,updated_at) VALUES(?,?,?,?,?,30,12000,100000,'draft',?,?,?,?)").bind(storeId,d.name,d.city,d.state,d.type,user.userId,d.description,now,now),
 db.prepare("INSERT INTO leads(id,partner_id,name,email,company,role,source,stage,next_step,notes,created_at,updated_at) VALUES(?,?,?,?,?,'retailer','Store submission','New','Review proposed store',?,?,?)").bind(`store_${storeId}`,user.userId,profile.name,user.email,d.name,`${d.city}, ${d.state}. ${d.description}`,now,now)
]);return json({ok:true,id:storeId})}
if(action==="referral.create"){if(profile?.role!=="distributor")return json({error:"Referral submission is available to distributor accounts."},403);const d=leadSchema.parse({...body.data,stage:"New",value_cents:0,owner:"",follow_up:"",next_step:"Review partner referral"});await db.prepare("INSERT INTO leads(id,referrer_id,name,email,company,role,source,stage,next_step,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,'Referral','New','Review partner referral',?,?,?)").bind(crypto.randomUUID(),user.userId,d.name,d.email,d.company,d.role,d.notes,now,now).run();return json({ok:true})}
if(!admin)return json({error:"This action is available only to the SWAY management team."},403);
if(action==="store.save"){const d=storeSchema.parse(body.data);const partnerId=d.partner_id||null;if(partnerId){const partner=await db.prepare("SELECT id FROM partners WHERE id=? AND role='retailer'").bind(partnerId).first();if(!partner)return json({error:"Choose a registered retailer for this store."},400)}
if(id){const result=await db.prepare("UPDATE stores SET name=?,city=?,state=?,type=?,capacity=?,monthly_cents=?,annual_cents=?,status=?,partner_id=?,description=?,updated_at=? WHERE id=? AND ?>=(SELECT COUNT(*) FROM requests WHERE store_id=? AND status='confirmed')").bind(d.name,d.city,d.state,d.type,d.capacity,d.monthly_cents,d.annual_cents,d.status,partnerId,d.description,now,id,d.capacity,id).run();if(!result.meta.changes)return json({error:"The store was not found, or capacity is below its confirmed placements."},409)}else{await db.prepare("INSERT INTO stores(id,name,city,state,type,capacity,monthly_cents,annual_cents,status,partner_id,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),d.name,d.city,d.state,d.type,d.capacity,d.monthly_cents,d.annual_cents,d.status,partnerId,d.description,now,now).run()}return json({ok:true})}
if(action==="request.review"){const status=z.enum(["confirmed","declined","cancelled"]).parse(body.status);const result=status==="confirmed"?await db.prepare("UPDATE requests SET status='confirmed',updated_at=? WHERE id=? AND status='requested' AND EXISTS(SELECT 1 FROM stores s WHERE s.id=requests.store_id AND s.status='published' AND s.capacity>(SELECT COUNT(*) FROM requests r WHERE r.store_id=s.id AND r.status='confirmed'))").bind(now,id).run():await db.prepare("UPDATE requests SET status=?,updated_at=? WHERE id=? AND (status='requested' OR (status='confirmed' AND ?='cancelled'))").bind(status,now,id,status).run();if(!result.meta.changes)return json({error:"The request changed, the store is not published, or no spots remain. Refresh and try again."},409);return json({ok:true})}
if(action==="lead.save"){const d=leadSchema.parse(body.data);if(id){const result=await db.prepare("UPDATE leads SET name=?,email=?,company=?,role=?,stage=?,next_step=?,follow_up=?,owner=?,value_cents=?,notes=?,updated_at=? WHERE id=?").bind(d.name,d.email,d.company,d.role,d.stage,d.next_step,d.follow_up,d.owner,d.value_cents,d.notes,now,id).run();if(!result.meta.changes)return json({error:"This lead no longer exists."},404)}else{await db.prepare("INSERT INTO leads(id,name,email,company,role,source,stage,next_step,follow_up,owner,value_cents,notes,created_at,updated_at) VALUES(?,?,?,?,?,'Manual',?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),d.name,d.email,d.company,d.role,d.stage,d.next_step,d.follow_up,d.owner,d.value_cents,d.notes,now,now).run()}return json({ok:true})}
return json({error:"Unknown action."},400);
}catch(e){if(e instanceof z.ZodError)return json({error:e.issues[0]?.message||"Please check the fields."},400);console.error("workspace_save_failed",e);return json({error:"Your changes could not be saved. Your form is still here—please try again."},503)}}
